/*

 BGTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 188

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define BGTilesBank 0

/* Super Gameboy palette 0 */
#define BGTilesSGBPal0c0 6076
#define BGTilesSGBPal0c1 8935
#define BGTilesSGBPal0c2 6596
#define BGTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define BGTilesSGBPal1c0 6076
#define BGTilesSGBPal1c1 8935
#define BGTilesSGBPal1c2 6596
#define BGTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define BGTilesSGBPal2c0 6076
#define BGTilesSGBPal2c1 8935
#define BGTilesSGBPal2c2 6596
#define BGTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define BGTilesSGBPal3c0 6076
#define BGTilesSGBPal3c1 8935
#define BGTilesSGBPal3c2 6596
#define BGTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define BGTilesCGBPal0c0 27615
#define BGTilesCGBPal0c1 9917
#define BGTilesCGBPal0c2 9657
#define BGTilesCGBPal0c3 8398

/* Gameboy Color palette 1 */
#define BGTilesCGBPal1c0 27615
#define BGTilesCGBPal1c1 23295
#define BGTilesCGBPal1c2 9917
#define BGTilesCGBPal1c3 9657

/* Gameboy Color palette 2 */
#define BGTilesCGBPal2c0 27615
#define BGTilesCGBPal2c1 23295
#define BGTilesCGBPal2c2 9657
#define BGTilesCGBPal2c3 8398

/* Gameboy Color palette 3 */
#define BGTilesCGBPal3c0 6076
#define BGTilesCGBPal3c1 8935
#define BGTilesCGBPal3c2 6596
#define BGTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define BGTilesCGBPal4c0 6076
#define BGTilesCGBPal4c1 8935
#define BGTilesCGBPal4c2 6596
#define BGTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define BGTilesCGBPal5c0 6076
#define BGTilesCGBPal5c1 8935
#define BGTilesCGBPal5c2 6596
#define BGTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define BGTilesCGBPal6c0 6076
#define BGTilesCGBPal6c1 8935
#define BGTilesCGBPal6c2 6596
#define BGTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define BGTilesCGBPal7c0 6076
#define BGTilesCGBPal7c1 8935
#define BGTilesCGBPal7c2 6596
#define BGTilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char BGTiles[];

/* End of BGTILES.H */
