/*

 MENU.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : wintiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define MenuMapWidth 20
#define MenuMapHeight 18
#define MenuMapBank 0

#define MenuMap MenuMapPLN0
extern const unsigned char MenuMapPLN0[];
extern const unsigned char MenuMapPLN1[];

/* End of MENU.H */
