/*

 SPRITES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 90

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define SpritesBank 0

/* Super Gameboy palette 0 */
#define SpritesSGBPal0c0 6076
#define SpritesSGBPal0c1 8935
#define SpritesSGBPal0c2 6596
#define SpritesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define SpritesSGBPal1c0 6076
#define SpritesSGBPal1c1 8935
#define SpritesSGBPal1c2 6596
#define SpritesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define SpritesSGBPal2c0 6076
#define SpritesSGBPal2c1 8935
#define SpritesSGBPal2c2 6596
#define SpritesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define SpritesSGBPal3c0 6076
#define SpritesSGBPal3c1 8935
#define SpritesSGBPal3c2 6596
#define SpritesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define SpritesCGBPal0c0 3114
#define SpritesCGBPal0c1 9917
#define SpritesCGBPal0c2 9657
#define SpritesCGBPal0c3 8398

/* Gameboy Color palette 1 */
#define SpritesCGBPal1c0 27615
#define SpritesCGBPal1c1 23295
#define SpritesCGBPal1c2 9917
#define SpritesCGBPal1c3 8398

/* Gameboy Color palette 2 */
#define SpritesCGBPal2c0 21342
#define SpritesCGBPal2c1 27615
#define SpritesCGBPal2c2 9657
#define SpritesCGBPal2c3 8398

/* Gameboy Color palette 3 */
#define SpritesCGBPal3c0 6076
#define SpritesCGBPal3c1 8935
#define SpritesCGBPal3c2 6596
#define SpritesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define SpritesCGBPal4c0 6076
#define SpritesCGBPal4c1 8935
#define SpritesCGBPal4c2 6596
#define SpritesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define SpritesCGBPal5c0 6076
#define SpritesCGBPal5c1 8935
#define SpritesCGBPal5c2 6596
#define SpritesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define SpritesCGBPal6c0 6076
#define SpritesCGBPal6c1 8935
#define SpritesCGBPal6c2 6596
#define SpritesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define SpritesCGBPal7c0 6076
#define SpritesCGBPal7c1 8935
#define SpritesCGBPal7c2 6596
#define SpritesCGBPal7c3 5344
/* Start of tile array. */
extern unsigned char Sprites[];

/* End of SPRITES.H */
