/*

 WINMAP.H

 Map Include File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 20 x 18
   Tile set      : wintiles.gbr
   Plane count   : 2 planes (16 bits)
   Plane order   : Planes are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define WinMapWidth 20
#define WinMapHeight 18
#define WinMapBank 0

#define WinMap WinMapPLN0
extern const unsigned char WinMapPLN0[];
extern const unsigned char WinMapPLN1[];

/* End of WINMAP.H */
