/*

 WINTILES.H

 Include File.

 Info:
  Form                 : All tiles as one unit.
  Format               : Gameboy 4 color.
  Compression          : None.
  Counter              : None.
  Tile size            : 8 x 8
  Tiles                : 0 to 153

  Palette colors       : Included.
  SGB Palette          : None.
  CGB Palette          : None.

  Convert to metatiles : No.

 This file was generated by GBTD v2.2

*/


/* Bank of tiles. */
#define WinTilesBank 0

/* Super Gameboy palette 0 */
#define WinTilesSGBPal0c0 6076
#define WinTilesSGBPal0c1 8935
#define WinTilesSGBPal0c2 6596
#define WinTilesSGBPal0c3 5344

/* Super Gameboy palette 1 */
#define WinTilesSGBPal1c0 6076
#define WinTilesSGBPal1c1 8935
#define WinTilesSGBPal1c2 6596
#define WinTilesSGBPal1c3 5344

/* Super Gameboy palette 2 */
#define WinTilesSGBPal2c0 6076
#define WinTilesSGBPal2c1 8935
#define WinTilesSGBPal2c2 6596
#define WinTilesSGBPal2c3 5344

/* Super Gameboy palette 3 */
#define WinTilesSGBPal3c0 6076
#define WinTilesSGBPal3c1 8935
#define WinTilesSGBPal3c2 6596
#define WinTilesSGBPal3c3 5344

/* Gameboy Color palette 0 */
#define WinTilesCGBPal0c0 27615
#define WinTilesCGBPal0c1 9917
#define WinTilesCGBPal0c2 9657
#define WinTilesCGBPal0c3 8398

/* Gameboy Color palette 1 */
#define WinTilesCGBPal1c0 27615
#define WinTilesCGBPal1c1 23295
#define WinTilesCGBPal1c2 9917
#define WinTilesCGBPal1c3 9657

/* Gameboy Color palette 2 */
#define WinTilesCGBPal2c0 27615
#define WinTilesCGBPal2c1 23295
#define WinTilesCGBPal2c2 9657
#define WinTilesCGBPal2c3 8398

/* Gameboy Color palette 3 */
#define WinTilesCGBPal3c0 6076
#define WinTilesCGBPal3c1 8935
#define WinTilesCGBPal3c2 6596
#define WinTilesCGBPal3c3 5344

/* Gameboy Color palette 4 */
#define WinTilesCGBPal4c0 6076
#define WinTilesCGBPal4c1 8935
#define WinTilesCGBPal4c2 6596
#define WinTilesCGBPal4c3 5344

/* Gameboy Color palette 5 */
#define WinTilesCGBPal5c0 6076
#define WinTilesCGBPal5c1 8935
#define WinTilesCGBPal5c2 6596
#define WinTilesCGBPal5c3 5344

/* Gameboy Color palette 6 */
#define WinTilesCGBPal6c0 6076
#define WinTilesCGBPal6c1 8935
#define WinTilesCGBPal6c2 6596
#define WinTilesCGBPal6c3 5344

/* Gameboy Color palette 7 */
#define WinTilesCGBPal7c0 6076
#define WinTilesCGBPal7c1 8935
#define WinTilesCGBPal7c2 6596
#define WinTilesCGBPal7c3 5344
/* Start of tile array. */
extern const unsigned char WinTiles[];

/* End of WINTILES.H */
